# Generated by Django 4.2.8 on 2024-01-09 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=12, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('gst_no', models.CharField(max_length=50, null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('person_of_contact', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('categories', models.CharField(max_length=255, null=True)),
                ('Remark', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Open'), (2, 'Close')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_quotations', to='api.buyer')),
                ('suppliers', models.ManyToManyField(related_name='request_quotations', to='api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='RequestForQuotationMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_conditions', models.TextField(null=True)),
                ('payment_terms', models.TextField(null=True)),
                ('shipping_terms', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Request_for_quotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_quotation_meta_data', to='api.requestquotation')),
            ],
        ),
        migrations.CreateModel(
            name='RequestForQuotationItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('uom', models.CharField(max_length=50, null=True)),
                ('specifications', models.TextField(null=True)),
                ('expected_delivery_date', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Request_for_quotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_quotation_items', to='api.requestquotation')),
            ],
        ),
    ]
