# Generated by Django 4.2.8 on 2024-01-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_buyer_address_alter_buyer_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='Remark',
            new_name='remark',
        ),
    ]
