# Generated by Django 4.2.8 on 2024-01-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_remark_supplier_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Open'), (2, 'Close')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_for_quotations', to='api.buyer')),
                ('suppliers', models.ManyToManyField(related_name='request_for_quotations', to='api.supplier')),
            ],
        ),
        migrations.RemoveField(
            model_name='requestforquotationitems',
            name='Request_for_quotation',
        ),
        migrations.RemoveField(
            model_name='requestforquotationmetadata',
            name='Request_for_quotation',
        ),
        migrations.AlterField(
            model_name='requestforquotationitems',
            name='product_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requestforquotationitems',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='RequestQuotation',
        ),
        migrations.AddField(
            model_name='requestforquotationitems',
            name='request_for_quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_for_quotation_items', to='api.requestforquotation'),
        ),
        migrations.AddField(
            model_name='requestforquotationmetadata',
            name='request_for_quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_for_quotation_meta_data', to='api.requestforquotation'),
        ),
    ]
