# Generated by Django 4.2.8 on 2024-01-24 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_requestforquotation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='categories',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='person_of_contact',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_categories', to='api.buyer')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='api.supplier')),
            ],
        ),
    ]
