# Generated by Django 4.2.8 on 2024-01-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_supplier_id_supplier_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='temp_id',
            new_name='id',
        ),
    ]
