# Generated by Django 4.2.8 on 2024-01-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_temp_id_supplier_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliercategory',
            name='supplier',
        ),
    ]
