# Generated by Django 4.2.8 on 2024-01-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_suppliercategory_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercategory',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='api.supplier'),
        ),
    ]
