# Generated by Django 4.2.8 on 2024-01-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_suppliercategory_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestforquotation',
            name='suppliers',
        ),
    ]
