# Generated by Django 4.2.8 on 2024-01-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_requestforquotation_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforquotation',
            name='suppliers',
            field=models.ManyToManyField(related_name='request_for_quotations', to='api.supplier'),
        ),
    ]
