# Generated by Django 4.2.8 on 2024-01-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_requestforquotation_suppliers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='Address',
            new_name='address',
        ),
    ]
