# Generated by Django 4.2.8 on 2024-01-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_address_buyer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestforquotation',
            name='status',
        ),
        migrations.AddField(
            model_name='requestforquotationitems',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Open'), (2, 'Close')], default=1),
        ),
    ]
