# Generated by Django 4.2.8 on 2024-01-29 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_requestforquotation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForQuotationItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('request_for_quotation_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_for_quotation_item_response', to='api.requestforquotationitems')),
            ],
        ),
    ]
