# Generated by Django 4.2.8 on 2024-01-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_requestforquotationitemresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforquotationitemresponse',
            name='order_status',
            field=models.SmallIntegerField(choices=[(2, 'Pending'), (1, 'Placed')], default=2),
        ),
    ]
