# Generated by Django 4.2.8 on 2024-01-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_requestforquotationitemresponse_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforquotationitemresponse',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_for_quotation_responses', to='api.supplier'),
        ),
    ]
