# Generated by Django 4.2.8 on 2024-02-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_requestforquotationitemresponse_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforquotationitemresponse',
            name='lead_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestforquotationitemresponse',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
