# Generated by Django 4.2.8 on 2025-01-21 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_requestforquotationitemresponse_lead_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="subscription_expiry_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buyer",
            name="test_user",
            field=models.BooleanField(default=False),
        ),
    ]
