# Generated by Django 4.2.8 on 2025-02-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_buyer_subscription_expiry_date_buyer_test_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
