# Generated by Django 4.2.8 on 2025-03-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_supplier_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="phone_no",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
