# Generated by Django 4.2.8 on 2025-04-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_buyer_phone_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="currency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
