# Generated by Django 4.2.8 on 2025-04-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_buyer_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestforquotationitemresponse",
            name="bought_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="requestforquotationitemresponse",
            name="bought_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
