# Generated by Django 4.2.8 on 2025-04-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_requestforquotationitemresponse_bought_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="phone_no",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
