# Generated by Django 5.2.7 on 2025-11-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_requestforquotation_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="onboarding_variant",
            field=models.CharField(
                choices=[
                    ("PAYWALL_FIRST", "Paywall First"),
                    ("TRIAL_FIRST", "Trial First"),
                ],
                default="TRIAL_FIRST",
                max_length=20,
            ),
        ),
    ]
