# Generated by Django 4.2.8 on 2025-11-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_buyer_onboarding_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="timezone",
            field=models.CharField(
                blank=True, default="Asia/Kolkata", max_length=100, null=True
            ),
        ),
    ]
